# I know that compose is used for multi container docker setup but this to demostrate declarative schematic
version: "3.6"
services:
    DockerCoreApp:
        container_name: first-compose-container
        ports:
            - 5003:80           
        image: ranjeethmd/open-image:first-docker-image 