apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc
spec:
  replicas: 20
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-pod
          image: ranjeethmd/open-image:secure-docker-image
          ports:
            - containerPort: 8080



    
