name: CI for .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --output public
    - uses: actions/upload-artifact@v2
      with:
        name: .NET build artifacts
        path: public/   
  test:
    runs-on: ubuntu-latest
    needs: build 
    strategy:
      matrix:
        dotnet-version: [3.1.x, 5.0.x]
        os: [ubuntu-latest, windows-2016]        
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: actions/download-artifact@v2
      with:
        name: .NET build artifacts          
    - name: Test
      run: dotnet test --no-build --verbosity normal
